// Builds index.html (what GitHub Pages serves) from index.src.html (what gets edited).
//
// index.src.html runs its app code through Babel in the browser, which made every phone download a
// ~3 MB compiler and compile ~3,000 lines on each open. The build compiles the JSX once here, drops
// Babel, and swaps React's development builds for the production ones.
//
//   node build.mjs          (needs Node 18+ and network access for npx esbuild on first run)

import { readFileSync, writeFileSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';

const SRC = 'index.src.html';
const OUT = 'index.html';
let html = readFileSync(SRC, 'utf8').replace(/\r\n/g, '\n');

// 1. compile the app script
const appRe = /<script type="text\/babel" data-presets="react">\n?([\s\S]*?)<\/script>/;
const m = html.match(appRe);
if (!m) throw new Error('app <script type="text/babel"> not found in ' + SRC);
// one command string (not an args array) — Windows needs a shell to run npx, and Node warns about
// passing an args array through a shell
const esb = spawnSync('npx --yes esbuild@0.24.0 --loader=jsx --target=es2019 --charset=utf8 --minify-whitespace --minify-syntax ' +
  '--jsx-factory=React.createElement --jsx-fragment=React.Fragment',
  { input: m[1], encoding: 'utf8', shell: true, maxBuffer: 64 * 1024 * 1024 });
if (esb.status !== 0) throw new Error('esbuild failed:\n' + esb.stderr);
// a literal "</script" inside the code would end the tag early; "<\/script" means the same in JS
const compiled = esb.stdout.replace(/<\/script/gi, '<\\/script');
// The trailing text/babel tag is inert (Babel is no longer loaded) but lets pages still running
// the old, unbuilt version notice the update: their updater looks for a text/babel script and
// reloads when its content differs. It must come after #app-code, which the current updater reads
html = html.replace(appRe, () => '<script id="app-code">' + compiled + '</script>\n' +
  '<script type="text/babel" data-presets="react">/* built — the app is in #app-code above */</script>');

// 2. no in-browser Babel any more
html = html.replace(/<script src="https:\/\/unpkg\.com\/@babel\/standalone[^"]*"[^>]*><\/script>\n?/, '');

// 3. React production builds (with subresource integrity computed from the files themselves)
for (const lib of ['react', 'react-dom']) {
  const devRe = new RegExp('<script src="https://unpkg\\.com/' + lib + '@([\\d.]+)/umd/' + lib + '\\.development\\.js"[^>]*></script>');
  const dm = html.match(devRe);
  if (!dm) throw new Error(lib + ' development script tag not found');
  const url = 'https://unpkg.com/' + lib + '@' + dm[1] + '/umd/' + lib + '.production.min.js';
  const res = await fetch(url);
  if (!res.ok) throw new Error('fetch ' + url + ': ' + res.status);
  const sri = 'sha384-' + createHash('sha384').update(Buffer.from(await res.arrayBuffer())).digest('base64');
  html = html.replace(devRe, '<script src="' + url + '" integrity="' + sri + '" crossorigin="anonymous"></script>');
}

// 4. mark the output as generated
html = html.replace('<!DOCTYPE html>\n', '<!DOCTYPE html>\n<!-- GENERATED by build.mjs from index.src.html — edit that file, then run: node build.mjs -->\n');

writeFileSync(OUT, html);
console.log(`${OUT}: ${(html.length / 1024).toFixed(0)} KB (app code ${(m[1].length / 1024).toFixed(0)} KB -> ${(compiled.length / 1024).toFixed(0)} KB)`);
